# Generated by Django 5.0.3 on 2024-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_auction', '0003_alter_cars_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
