# Generated by Django 5.0.3 on 2024-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_auction', '0004_alter_cars_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='p.png', upload_to='uploads'),
        ),
    ]
