# Generated by Django 5.0.3 on 2024-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_auction', '0005_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
